[package]
name = "cmd_switch"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.24", features = ["env", "derive"] }
thiserror = "1.0.40"
tryhard = "0.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.96"
termimad = "0.20"

